version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories: # Location of Julia projects
      - "/"
      - "/docs
    schedule:
      interval: "weekly"
    # groups: # uncomment to group all julia package updates into a single PR
    #   all-julia-packages:
    #     patterns:
    #       - "*"